version: '{build}'
image: Visual Studio 2017
pull_requests:  
  do_not_increment_build_number: true
before_build:
- cmd: dotnet --version
build_script:  
- ps: .\build.ps1
test: off
artifacts:  
- path: .\artifacts\**\*.*
deploy: off